image: docker:latest

build:
  stage: build
  script:
    - docker build -t test .

test:
  stage: test
  script:
    - docker build -t test-luigi .
    - docker run --volume $(pwd):/app:ro --entrypoint "./scripts/run_test.sh"
