image: docker:latest

build:
  tags:
    - barberini
  script:
    - docker build -t test .

test:
  tags:
    - barberini
  script:
    - container=$(docker ps -f name=gitlab-runner-luigi -q)
    - if [ -n "$container" ]; then docker stop $container && docker rm $container; fi
    - make startup
    - docker exec --env FULL_TEST=$FULL_TEST gitlab-runner-luigi make test  
    - make shutdown

lint:
  tags:
    - barberini
  script:
    - python3 -m pip install flake8 --user
    - python3 -m flake8 -v --show-source .

coverage:
  tags:
    - barberini
  script:
    - container=$(docker ps -f name=gitlab-runner-luigi -q)
    - if [ -n "$container" ]; then docker stop $container && docker rm $container; fi
    - make startup
    - docker exec --env FULL_TEST=$FULL_TEST gitlab-runner-luigi make coverage  
    - make shutdown
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    paths: 
      - htmlcov
