image: docker:latest

variables:
  BARBERINI_ANALYTICS_CONTEXT: CI

# Stages are required a) to priorize jobs and b) to avoid concurrency issues.
stages:
  - build
  - test
  - analyze

build:
  stage: build
  tags:
    - barberini
  script:
    - docker build -t test .

coverage:
  stage: test
  tags:
    - barberini
  script:
    - container=$(docker ps -f name=gitlab-runner-barberini_analytics_luigi -q)
    - if [ -n "$container" ]; then docker stop $container && docker rm $container; fi
    - make startup
    - docker exec --env FULL_TEST=$FULL_TEST gitlab-runner-barberini_analytics_luigi make coverage  
    - make shutdown
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    paths: 
      - htmlcov

lint:
  stage: analyze
  tags:
    - barberini
  script:
    - python3 -m pip install flake8 --user
    - python3 -m flake8 -v --show-source .

minimal-mining-pipeline:
  stage: test
  script:
    - ./scripts/tests/run_minimal_mining_pipeline.sh
