image: docker:latest

# Stages are required a) to priorize jobs and b) to avoid concurrency issues.
stages:
  - build
  - test
  - analyze

build:
  stage: build
  tags:
    - barberini
  script:
    - docker build -t test .

coverage:
  stage: test
  tags:
    - barberini
  script:
    - container=$(docker ps -f name=gitlab-runner-luigi -q)
    - if [ -n "$container" ]; then docker stop $container && docker rm $container; fi
    - make startup
    - docker exec --env FULL_TEST=$FULL_TEST gitlab-runner-luigi make coverage  
    - make shutdown
  coverage: '/TOTAL\s+\d+\s+\d+\s+(\d+%)/'
  artifacts:
    paths: 
      - htmlcov

lint:
  stage: analyze
  tags:
    - barberini
  script:
    - python3 -m pip install flake8 --user
    - python3 -m flake8 -v --show-source .

mining-pipeline:
  stage: test
  script:
    - ./scripts/tests/run_minimal_mining_pipeline.sh
  artifacts:
    paths: 
      - schema.output

# Deprecated, see #145. Moving this to the bottom of CI for now in order to
# detect possible problems with the coverage job as failure detector.
test:
  stage: analyze
  tags:
    - barberini
  script:
    - container=$(docker ps -f name=gitlab-runner-luigi -q)
    - if [ -n "$container" ]; then docker stop $container && docker rm $container; fi
    - make startup
    - docker exec --env FULL_TEST=$FULL_TEST gitlab-runner-luigi make test
    - make shutdown

