image: docker:latest

build:
  stage: build
  script:
    - docker build -t test .

test:
  stage: test
  script:
    - make startup
    - docker exec gitlab-runner-luigi make test  
    - make shutdown
