image: docker:latest

build:
  stage: build
  script:
    - docker build -t test .

test:
  stage: test
  script:
    - make startup
    - docker-compose -p gitlab-runner exec luigi make test 
    - make shutdown
