image: docker:latest

variables:
  BARBERINI_ANALYTICS_CONTEXT: CI

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_IID
    - if: $CI_COMMIT_TAG
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH  
  
# Stages are required a) to priorize jobs and b) to avoid concurrency issues.
stages:
  - build
  - test
  - analyze

build:
  stage: build
  tags:
    - barberini
  script:
    - docker build -t test ./docker

lint:
  stage: analyze
  tags:
    - barberini
  script:
    - make lint

test-pbi-reports:
  stage: test
  rules:
    - if: '$FULL_TEST'
      when: always
    - if: '$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME =~ /.*test-powerbi.*/ && $CI_MERGE_REQUEST_TITLE =~ /WIP: .*/'
      when: always
  tags:
    - bernd-windows
  before_script:
    - powershell -Command "&scripts/setup/install_powershell_deps.ps1"
  script:
    - powershell -Command "&tests/pbi_reports/test_pbi_reports.ps1"
  artifacts:
    when: always
    paths:
      - ./output/test_pbi/
