version: "3"

services:
        luigi:
                container_name: luigi
                build: .
                volumes:
                        - .:/app
                        - /etc/secrets/secret_files:/app/secret_files
                ports:
                        - "8082:8082"
                environment:
                        - PYTHONIOENCODING=utf-8
                env_file:
                        - /etc/secrets/keys.env
                        - /etc/secrets/database.env
                stdin_open: true
                tty: true

        db:
                container_name: db
                image: postgres
                ports:
                        - "5432:5432"
                env_file:
                        - /etc/secrets/database.env
                volumes:
                        - ./volumes/test:/var/lib/postgresql/data/

