version: "3.7"

services:
        luigi:
                container_name: ${USER}-luigi
                build: .
                volumes:
                        - .:/app
                ports:
                        - "8082"
                environment:
                        - PYTHONIOENCODING=utf-8
                        - PYTHONUNBUFFERED=1
                env_file:
                        - /etc/secrets/keys.env
                        - /etc/secrets/database.env
                stdin_open: true
                tty: true
                networks:
                        - database_network

        db:
                container_name: db
                image: postgres
                restart: always
                ports:
                        - "5432:5432"
                env_file:
                        - /etc/secrets/database.env
                volumes:
                        - /var/db-data/:/var/lib/postgresql/data/
                networks:
                        - database_network

networks:
        database_network:
                external: true
