# Extension files:
#       docker-compose-enable-ssl.yml

version: "3.7"

services:
    luigi:
        container_name: ${USER}-luigi
        hostname: ${HOSTNAME}
        build: .
        volumes:
            - .:/app
            - /etc/secrets/secret_files:/app/secret_files
        ports:
            - "8082"
        environment:
            - PYTHONIOENCODING=utf-8
            - PYTHONUNBUFFERED=1
            - PYTHONPATH=./src/:./src/_utils/
            - CONTAINER_USER=${USER}  # used to determine name of gplay_api container
        env_file:
            - /etc/secrets/keys.env
            - /etc/secrets/database.env
            - /etc/secrets/smtp.env
            - /etc/secrets/params.env
        stdin_open: true
        tty: true
        networks:
            - database_network

    db:
        container_name: db
        image: postgres
        restart: always
        ports:
            - "5432:5432"
        env_file:
            - /etc/secrets/database.env
        volumes:
            - /var/db-data/:/var/lib/postgresql/data/
        networks:
            - database_network

    gplay_api:
        # consider how the gplay api is called from gplay_reviews.py before renaming the container.
        container_name: ${USER}-gplay-api
        build:
            dockerfile: Dockerfile_gplay_api
            context: .
        networks:
            - database_network

networks:
    database_network:
        external: true
