version: "3"

services:
        luigi:
                container_name: luigi
                build: .
                volumes:
                        - .:/app
                ports:
                        - "8082:8082"
                environment:
                        - PYTHONIOENCODING=utf-8
                env_file:
                        - /etc/secrets.env
                stdin_open: true
                tty: true

        db:
                container_name: db
                image: postgres
                ports:
                        - "5432:5432"
                environment: 
                        - PGDATA=/var/lib/postgresql/data/pg-data/
                        - POSTGRES_USER=postgres
                        - POSTGRES_PASSWORD=docker
                        - POSTGRES_DB=barberini
                volumes:
                        - ./volumes/test:/var/lib/postgresql/data/

