# This is an extension file, intended for use
# together with the main 'docker-compose.yml'

version: "3.7"

services:
    barberini_analytics_db:
        # -c provides the postgres instance inside the container
        # with configuration options, equal to setting them in
        # a 'postgresql.conf' file
        command: >
            -c ssl=on
            -c ssl_cert_file=/var/lib/postgresql/data/server.crt
            -c ssl_key_file=/var/lib/postgresql/data/server.key
